config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "influencers#index"
  resources :influencers, only: %i[index create show new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/influencer.rb
class Influencer < ApplicationRecord
  validates :username, uniqueness: { scope: :platform }
  validates :external_id, uniqueness: { scope: :platform }, allow_nil: true
  validates :username, :fullname, :picture, :followers, :platform, presence: true
  validates :is_verified, inclusion: { in: [true, false] }
  validates :picture, format: { with: Rack::Utils::URI_PARSER.make_regexp }
  validates :followers, numericality: { only_integer: true }

  enum :platform, { youtube: 0, instagram: 1, tiktok: 2 }

  scope :ordered, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
  def index
    ImportInfluencersJob.perform_later unless Influencer.exists?(is_manual: false)
    @influencers = Influencer.ordered.page(params[:page]).per(8)

    if params[:query].present?
      @influencers = @influencers.where("fullname iLIKE ?", "%#{params[:query]}%")
    end
  end

  def create
    @influencer = Influencer.new(influencer_params)

    respond_to do |format|
      if @influencer.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("influencers", partial: "influencers/influencer", locals: { influencer: @influencer })
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def new
    @influencer = Influencer.new
  end

  private

  def influencer_params
    params.expect(influencer: %i[external_id username fullname picture followers is_verified platform])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/influencer_helper.rb
module InfluencerHelper
  def influencer_is_verified(influencer)
    influencer.is_verified ? "check.png" : "mark.png"
  end
end

app/views/influencers/_form.html.erb
<%= form_with model: influencer, url: influencers_path, method: :post do |f| %>
  <div class="border-b border-gray-900/10 pb-12">
    <div class="space-y-12">
      <fieldset>
        <% if influencer.errors.any? %>
          <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
            <legend class="text-sm/6 font-semibold"><%= t("influencers.errors", count: pluralize(influencer.errors.count, "error")) %>:</legend>

            <ul>
              <% influencer.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </fieldset>

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8">
        <div class="sm:col-span-4">
          <%= f.label :username, t("influencers.username"), class: "block text-sm/6 font-medium text-gray-900" %>
          <div class="mt-2">
            <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600">
              <%= f.text_field :username, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6", placeholder: "pewdiepie" %>
            </div>
          </div>
        </div>

        <div class="sm:col-span-4">
          <%= f.label :fullname, t("influencers.fullname"), class: "block text-sm/6 font-medium text-gray-900" %>
          <div class="mt-2">
            <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600">
              <%= f.text_field :fullname, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6", placeholder: "The Rock" %>
            </div>
          </div>
        </div>

        <div class="sm:col-span-4">
          <%= f.label :picture, t("influencers.picture"), class: "block text-sm/6 font-medium text-gray-900" %>
          <div class="mt-2">
            <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600">
              <%= f.text_field :picture, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6", placeholder: "https://i.pravatar.cc/150?img=35" %>
            </div>
          </div>
        </div>

        <div class="sm:col-span-4">
          <%= f.label :followers, t("influencers.followers_number"), class: "block text-sm/6 font-medium text-gray-900" %>
          <div class="mt-2">
            <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600">
              <%= f.text_field :followers, type: 'number', class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6", placeholder: "50000" %>
            </div>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= f.label :platform, t("influencers.platform"), class: "block text-sm/6 font-medium text-gray-900" %>
          <div class="mt-2 grid grid-cols-1">
            <%= f.select :platform, Influencer.platforms.keys.map { |platform| [platform.titleize, platform] }, { },
                          class: "col-start-1 row-start-1 w-full appearance-none rounded-md bg-white py-1.5 pr-8 pl-3 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" %>
            <svg class="pointer-events-none col-start-1 row-start-1 mr-2 size-5 self-center justify-self-end text-gray-500 sm:size-4" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" data-slot="icon">
              <path fill-rule="evenodd" d="M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
            </svg>
          </div>
        </div>

        <div class="sm:col-span-4">
          <%= f.hidden_field :is_verified, value: 0 %>

          <div class="mt-2">
            <div class="flex items-center">
              <%= f.check_box :is_verified, class: "toggle block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6", id: "snippet_is_verified" %>
              <%= f.label :is_verified, t("influencers.verified_account"), class: "optional block text-sm/6 font-medium text-gray-900", for: "snippet_is_verified" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <button type="button" class="text-sm/6 font-semibold text-gray-900 cursor-pointer" data-action="click->dialog#close"><%= t("close") %></button>
    <%= f.submit t("influencers.button_new"), class: 'cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"' %>
  </div>
<% end %>

app/views/influencers/_influencer.html.erb
<div id="influencer_<%= influencer.id %>" class="bg-white shadow-lg rounded-lg overflow-hidden hover:shadow-xl transition-shadow duration-300">
  <div class="w-full h-48 overflow-hidden">
    <%= image_tag influencer.picture, alt: influencer.username, class: "w-full h-full object-cover" %>
  </div>

  <div class="p-4">
    <h3 class="text-lg font-semibold text-gray-900"><%= influencer.username %></h3>
    <p class="text-sm text-gray-600"><%= influencer.fullname %></p>

    <div class="mt-4">
      <p class="text-sm text-gray-500">
        <span class="font-medium"><%= t("influencers.followers") %>:</span>
        <%= number_with_delimiter(influencer.followers) %>
      </p>
      <p class="text-sm text-gray-500">
        <span class="font-medium"><%= t("influencers.platform") %>:</span>
        <%= influencer.platform.capitalize %>
      </p>
      <p class="text-sm text-gray-500 flex items-center">
        <span class="font-medium mr-2"><%= t("influencers.is_verified") %>:</span>
        <%= image_tag influencer_is_verified(influencer), alt: t("influencers.is_verified_photo"), height: 12, width: 12 %>
      </p>
    </div>
  </div>
</div>

app/views/influencers/_list.html.erb
<div id="influencers" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
  <% influencers.each do |influencer| %>
    <%= render influencer %>
  <% end %>
</div>

app/views/influencers/_search_bar.html.erb
<%= form_with url: "/influencers", method: :get, html: { class: "max-w-md" } do |f| %>
  <div class="relative">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
      </svg>
    </div>
    <%= f.text_field :query, placeholder: "Buscar influencer", class: "block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:border-gray-600 dark:placeholder-gray-400 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    <%= f.submit t("search"), name: nil, class: "text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 cursor-pointer" %>
  </div>
<% end %>

app/views/influencers/index.html.erb
<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-10 flex justify-center text-gray-900"><%= t("influencers.index") %></h1>

  <section class="mb-6 flex justify-between items-center">
    <div class="flex-1 justify-self-start">
      <%= render 'search_bar' %>
    </div>
    <div class="flex-none justify-self-end">
      <%= link_to t("influencers.button_new"),
                  new_influencer_path,
                  class: "bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-4 px-4 rounded-lg shadow",
                  data: { turbo_frame: :new_influencer, action: "click->dialog#open" } %>
      <%= turbo_frame_tag :new_influencer %>
    </div>
  </section>

  <%= turbo_frame_tag :influencers_index do %>
    <%= render "influencers/list", influencers: @influencers %>
    <div class="mt-6">
      <%= paginate @influencers, theme: 'tailwind', influencers: @influencers %>
    </div>
  <% end %>

  <%= turbo_stream_from :influencers_list %>
</div>

app/views/influencers/new.html.erb
<%= render 'layouts/turbo_dialog' do %>
  <div data-action="turbo:submit-end->dialog#submitEnd">
    <h1 class="font-bold text-4xl flex justify-center text-gray-900"><%= t("influencers.new") %></h1>
    <%= render "form", influencer: @influencer %>
  </div>
<% end %>

app/views/layouts/_turbo_dialog.html.erb
<%= turbo_frame_tag :new_influencer do %>
  <dialog data-controller="dialog" data-action="click->dialog#clickOutside"
          class="backdrop:bg-gray-400 backdrop:bg-opacity-90 z-10 rounded-md border-4w-full md:w-2/3 m-auto">
    <div class="p-8">
      <%= yield %>
    </div>
  </dialog>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Influencers Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-6 px-5">
      <%= yield %>
    </main>

    <%= turbo_frame_tag :new_influencer %>
  </body>
</html>